version: '3.8'

services:
  notion-generator:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HF_API_KEY=${HF_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
